# Introduction

This notebook is intended to prove out the feasibility of my final project for NYU Summer 2026 Intro to Python Programming Class (Prof M Rosetti). My project intends to solve a  problem I myself am facing as an amateur gardener, which is the lack of a searchable database of plants that allows me to select certain inputs (light requirements, USDA plant hardiness zones, and a few other filters) and get an output that is a list of plants that meets that criteria with basic info (colloquial name, scientific name, basic description, image). Additionally, once I find plants that I might want to add to my garden, I want to be able to save those plants and tag them. This is potentially the start of an app that could be expanded at a later time to solve for things like a digital gardening journal that allows me to note date planted, success/fail, recommendations to self for next year, etc. Ultimately, the app could be monetized in a few different ways: one-time download fee from app store; monthly subscription fee required to save lists and notes; adding a marketplace feature and a revenue share with box stores and nurseries where end users can buy plants.

# Approach to API and Data Investigation

Although I haven't yet fully finalized my requirements, I want to investigate which APIs can get me closest to including the following:

Inputs:
1. Light requirements
2. Whether the plant is edible
3. Hardiness zone where the plant is native, and where the plant can survive year-round

Outputs:
1. Image
2. Description
3. Name (scientific and informal)

# Trefle API

First, I got an API key and tried to see what I could use from Trefle API. Documentation is available here: https://docs.trefle.io/docs/guides/getting-started

# Trefle API Setup & Investigation (API Key)

In [ ]:
from google.colab import userdata

TREFLE_API_KEY = userdata.get("TREFLE_API")

In [ ]:
# JSON:
trefle_request_url = f"https://trefle.io/api/v1/genus?token={TREFLE_API_KEY}"

In [ ]:
import requests

trefle_response = requests.get(trefle_request_url)
print(trefle_response)
print(trefle_response.json())

<Response [200]>
{'data': [{'id': 2552, 'name': 'Aa', 'slug': 'aa', 'links': {'self': '/api/v1/genus/aa', 'plants': '/api/v1/genus/aa/plants', 'species': '/api/v1/genus/aa/species', 'family': '/api/v1/families/orchidaceae'}, 'family': {'id': 50, 'name': 'Orchidaceae', 'common_name': None, 'slug': 'orchidaceae', 'links': {'self': '/api/v1/families/orchidaceae', 'division_order': None, 'genus': '/api/v1/families/orchidaceae/genus'}}}, {'id': 15299, 'name': 'Aakia', 'slug': 'aakia', 'links': {'self': '/api/v1/genus/aakia', 'plants': '/api/v1/genus/aakia/plants', 'species': '/api/v1/genus/aakia/species', 'family': '/api/v1/families/poaceae'}, 'family': {'id': 7, 'name': 'Poaceae', 'common_name': None, 'slug': 'poaceae', 'links': {'self': '/api/v1/families/poaceae', 'division_order': None, 'genus': '/api/v1/families/poaceae/genus'}}}, {'id': 600, 'name': 'Aaronsohnia', 'slug': 'aaronsohnia', 'links': {'self': '/api/v1/genus/aaronsohnia', 'plants': '/api/v1/genus/aaronsohnia/plants', 'species': '/api/v1/genus/aaronsohnia/species', 'family': '/api/v1/families/asteraceae'}, 'family': {'id': 13, 'name': 'Asteraceae', 'common_name': 'Aster family', 'slug': 'asteraceae', 'links': {'self': '/api/v1/families/asteraceae', 'division_order': '/api/v1/division_orders/asterales', 'genus': '/api/v1/families/asteraceae/genus'}}}, {'id': 15699, 'name': 'Abacopteris', 'slug': 'abacopteris', 'links': {'self': '/api/v1/genus/abacopteris', 'plants': '/api/v1/genus/abacopteris/plants', 'species': '/api/v1/genus/abacopteris/species', 'family': None}, 'family': None}, {'id': 2124, 'name': 'Abarema', 'slug': 'abarema', 'links': {'self': '/api/v1/genus/abarema', 'plants': '/api/v1/genus/abarema/plants', 'species': '/api/v1/genus/abarema/species', 'family': '/api/v1/families/fabaceae'}, 'family': {'id': 49, 'name': 'Fabaceae', 'common_name': None, 'slug': 'fabaceae', 'links': {'self': '/api/v1/families/fabaceae', 'division_order': None, 'genus': '/api/v1/families/fabaceae/genus'}}}, {'id': 11586, 'name': 'Abatia', 'slug': 'abatia', 'links': {'self': '/api/v1/genus/abatia', 'plants': '/api/v1/genus/abatia/plants', 'species': '/api/v1/genus/abatia/species', 'family': '/api/v1/families/salicaceae'}, 'family': {'id': 434, 'name': 'Salicaceae', 'common_name': None, 'slug': 'salicaceae', 'links': {'self': '/api/v1/families/salicaceae', 'division_order': None, 'genus': '/api/v1/families/salicaceae/genus'}}}, {'id': 7228, 'name': 'Abdra', 'slug': 'abdra', 'links': {'self': '/api/v1/genus/abdra', 'plants': '/api/v1/genus/abdra/plants', 'species': '/api/v1/genus/abdra/species', 'family': '/api/v1/families/brassicaceae'}, 'family': {'id': 8, 'name': 'Brassicaceae', 'common_name': None, 'slug': 'brassicaceae', 'links': {'self': '/api/v1/families/brassicaceae', 'division_order': None, 'genus': '/api/v1/families/brassicaceae/genus'}}}, {'id': 15891, 'name': 'Abelia', 'slug': 'abelia', 'links': {'self': '/api/v1/genus/abelia', 'plants': '/api/v1/genus/abelia/plants', 'species': '/api/v1/genus/abelia/species', 'family': '/api/v1/families/caprifoliaceae'}, 'family': {'id': 126, 'name': 'Caprifoliaceae', 'common_name': None, 'slug': 'caprifoliaceae', 'links': {'self': '/api/v1/families/caprifoliaceae', 'division_order': None, 'genus': '/api/v1/families/caprifoliaceae/genus'}}}, {'id': 10537, 'name': 'Abeliophyllum', 'slug': 'abeliophyllum', 'links': {'self': '/api/v1/genus/abeliophyllum', 'plants': '/api/v1/genus/abeliophyllum/plants', 'species': '/api/v1/genus/abeliophyllum/species', 'family': '/api/v1/families/oleaceae'}, 'family': {'id': 264, 'name': 'Oleaceae', 'common_name': 'Olive family', 'slug': 'oleaceae', 'links': {'self': '/api/v1/families/oleaceae', 'division_order': '/api/v1/division_orders/scrophulariales', 'genus': '/api/v1/families/oleaceae/genus'}}}, {'id': 7229, 'name': 'Abelmoschus', 'slug': 'abelmoschus', 'links': {'self': '/api/v1/genus/abelmoschus', 'plants': '/api/v1/genus/abelmoschus/plants', 'species': '/api/v1/genus/abelmoschus/species', 'family': '/api/v1/families/malvaceae'}, 'family': {'id': 115, 'name': 'Malvaceae', 'common_name': None, 'slug': 'malvaceae', 'links': {'self': '/api/v1/families/malvaceae', 'division_order': None, 'genus': '/api/v1/families/malvaceae/genus'}}}, {'id': 7230, 'name': 'Abies', 'slug': 'abies', 'links': {'self': '/api/v1/genus/abies', 'plants': '/api/v1/genus/abies/plants', 'species': '/api/v1/genus/abies/species', 'family': '/api/v1/families/pinaceae'}, 'family': {'id': 3, 'name': 'Pinaceae', 'common_name': 'Pine family', 'slug': 'pinaceae', 'links': {'self': '/api/v1/families/pinaceae', 'division_order': '/api/v1/division_orders/pinales', 'genus': '/api/v1/families/pinaceae/genus'}}}, {'id': 13431, 'name': 'Abietinella', 'slug': 'abietinella', 'links': {'self': '/api/v1/genus/abietinella', 'plants': '/api/v1/genus/abietinella/plants', 'species': '/api/v1/genus/abietinella/species', 'family': '/api/v1/families/thuidiaceae'}, 'family': {'id': 501, 'name': 'Thuidiaceae', 'common_name': None, 'slug': 'thuidiaceae', 'links': {'self': '/api/v1/families/thuidiaceae', 'division_order': None, 'genus': '/api/v1/families/thuidiaceae/genus'}}}, {'id': 15885, 'name': 'Abildgaardia', 'slug': 'abildgaardia', 'links': {'self': '/api/v1/genus/abildgaardia', 'plants': '/api/v1/genus/abildgaardia/plants', 'species': '/api/v1/genus/abildgaardia/species', 'family': '/api/v1/families/cyperaceae'}, 'family': {'id': 5, 'name': 'Cyperaceae', 'common_name': 'Sedge family', 'slug': 'cyperaceae', 'links': {'self': '/api/v1/families/cyperaceae', 'division_order': '/api/v1/division_orders/cyperales', 'genus': '/api/v1/families/cyperaceae/genus'}}}, {'id': 7231, 'name': 'Abobra', 'slug': 'abobra', 'links': {'self': '/api/v1/genus/abobra', 'plants': '/api/v1/genus/abobra/plants', 'species': '/api/v1/genus/abobra/species', 'family': '/api/v1/families/cucurbitaceae'}, 'family': {'id': 144, 'name': 'Cucurbitaceae', 'common_name': None, 'slug': 'cucurbitaceae', 'links': {'self': '/api/v1/families/cucurbitaceae', 'division_order': None, 'genus': '/api/v1/families/cucurbitaceae/genus'}}}, {'id': 4199, 'name': 'Abolboda', 'slug': 'abolboda', 'links': {'self': '/api/v1/genus/abolboda', 'plants': '/api/v1/genus/abolboda/plants', 'species': '/api/v1/genus/abolboda/species', 'family': '/api/v1/families/xyridaceae'}, 'family': {'id': 97, 'name': 'Xyridaceae', 'common_name': None, 'slug': 'xyridaceae', 'links': {'self': '/api/v1/families/xyridaceae', 'division_order': None, 'genus': '/api/v1/families/xyridaceae/genus'}}}, {'id': 14778, 'name': 'Abrahamia', 'slug': 'abrahamia', 'links': {'self': '/api/v1/genus/abrahamia', 'plants': '/api/v1/genus/abrahamia/plants', 'species': '/api/v1/genus/abrahamia/species', 'family': '/api/v1/families/anacardiaceae'}, 'family': {'id': 134, 'name': 'Anacardiaceae', 'common_name': None, 'slug': 'anacardiaceae', 'links': {'self': '/api/v1/families/anacardiaceae', 'division_order': None, 'genus': '/api/v1/families/anacardiaceae/genus'}}}, {'id': 15671, 'name': 'Abrodictyum', 'slug': 'abrodictyum', 'links': {'self': '/api/v1/genus/abrodictyum', 'plants': '/api/v1/genus/abrodictyum/plants', 'species': '/api/v1/genus/abrodictyum/species', 'family': None}, 'family': None}, {'id': 7232, 'name': 'Abroma', 'slug': 'abroma', 'links': {'self': '/api/v1/genus/abroma', 'plants': '/api/v1/genus/abroma/plants', 'species': '/api/v1/genus/abroma/species', 'family': '/api/v1/families/malvaceae'}, 'family': {'id': 115, 'name': 'Malvaceae', 'common_name': None, 'slug': 'malvaceae', 'links': {'self': '/api/v1/families/malvaceae', 'division_order': None, 'genus': '/api/v1/families/malvaceae/genus'}}}, {'id': 7233, 'name': 'Abronia', 'slug': 'abronia', 'links': {'self': '/api/v1/genus/abronia', 'plants': '/api/v1/genus/abronia/plants', 'species': '/api/v1/genus/abronia/species', 'family': '/api/v1/families/nyctaginaceae'}, 'family': {'id': 192, 'name': 'Nyctaginaceae', 'common_name': None, 'slug': 'nyctaginaceae', 'links': {'self': '/api/v1/families/nyctaginaceae', 'division_order': None, 'genus': '/api/v1/families/nyctaginaceae/genus'}}}, {'id': 7235, 'name': 'Abrophyllum', 'slug': 'abrophyllum', 'links': {'self': '/api/v1/genus/abrophyllum', 'plants': '/api/v1/genus/abrophyllum/plants', 'species': '/api/v1/genus/abrophyllum/species', 'family': '/api/v1/families/rousseaceae'}, 'family': {'id': 296, 'name': 'Rousseaceae', 'common_name': None, 'slug': 'rousseaceae', 'links': {'self': '/api/v1/families/rousseaceae', 'division_order': None, 'genus': '/api/v1/families/rousseaceae/genus'}}}], 'links': {'self': '/api/v1/genus', 'first': '/api/v1/genus?page=1', 'next': '/api/v1/genus?page=2', 'last': '/api/v1/genus?page=826'}, 'meta': {'total': 16508}}

In [ ]:
trefle_data = trefle_response.json()
trefle_data

{'data': [{'id': 2552,
   'name': 'Aa',
   'slug': 'aa',
   'links': {'self': '/api/v1/genus/aa',
    'plants': '/api/v1/genus/aa/plants',
    'species': '/api/v1/genus/aa/species',
    'family': '/api/v1/families/orchidaceae'},
   'family': {'id': 50,
    'name': 'Orchidaceae',
    'common_name': None,
    'slug': 'orchidaceae',
    'links': {'self': '/api/v1/families/orchidaceae',
     'division_order': None,
     'genus': '/api/v1/families/orchidaceae/genus'}}},
  {'id': 15299,
   'name': 'Aakia',
   'slug': 'aakia',
   'links': {'self': '/api/v1/genus/aakia',
    'plants': '/api/v1/genus/aakia/plants',
    'species': '/api/v1/genus/aakia/species',
    'family': '/api/v1/families/poaceae'},
   'family': {'id': 7,
    'name': 'Poaceae',
    'common_name': None,
    'slug': 'poaceae',
    'links': {'self': '/api/v1/families/poaceae',
     'division_order': None,
     'genus': '/api/v1/families/poaceae/genus'}}},
  {'id': 600,
   'name': 'Aaronsohnia',
   'slug': 'aaronsohnia',
   'links': {'self': '/api/v1/genus/aaronsohnia',
    'plants': '/api/v1/genus/aaronsohnia/plants',
    'species': '/api/v1/genus/aaronsohnia/species',
    'family': '/api/v1/families/asteraceae'},
   'family': {'id': 13,
    'name': 'Asteraceae',
    'common_name': 'Aster family',
    'slug': 'asteraceae',
    'links': {'self': '/api/v1/families/asteraceae',
     'division_order': '/api/v1/division_orders/asterales',
     'genus': '/api/v1/families/asteraceae/genus'}}},
  {'id': 15699,
   'name': 'Abacopteris',
   'slug': 'abacopteris',
   'links': {'self': '/api/v1/genus/abacopteris',
    'plants': '/api/v1/genus/abacopteris/plants',
    'species': '/api/v1/genus/abacopteris/species',
    'family': None},
   'family': None},
  {'id': 2124,
   'name': 'Abarema',
   'slug': 'abarema',
   'links': {'self': '/api/v1/genus/abarema',
    'plants': '/api/v1/genus/abarema/plants',
    'species': '/api/v1/genus/abarema/species',
    'family': '/api/v1/families/fabaceae'},
   'family': {'id': 49,
    'name': 'Fabaceae',
    'common_name': None,
    'slug': 'fabaceae',
    'links': {'self': '/api/v1/families/fabaceae',
     'division_order': None,
     'genus': '/api/v1/families/fabaceae/genus'}}},
  {'id': 11586,
   'name': 'Abatia',
   'slug': 'abatia',
   'links': {'self': '/api/v1/genus/abatia',
    'plants': '/api/v1/genus/abatia/plants',
    'species': '/api/v1/genus/abatia/species',
    'family': '/api/v1/families/salicaceae'},
   'family': {'id': 434,
    'name': 'Salicaceae',
    'common_name': None,
    'slug': 'salicaceae',
    'links': {'self': '/api/v1/families/salicaceae',
     'division_order': None,
     'genus': '/api/v1/families/salicaceae/genus'}}},
  {'id': 7228,
   'name': 'Abdra',
   'slug': 'abdra',
   'links': {'self': '/api/v1/genus/abdra',
    'plants': '/api/v1/genus/abdra/plants',
    'species': '/api/v1/genus/abdra/species',
    'family': '/api/v1/families/brassicaceae'},
   'family': {'id': 8,
    'name': 'Brassicaceae',
    'common_name': None,
    'slug': 'brassicaceae',
    'links': {'self': '/api/v1/families/brassicaceae',
     'division_order': None,
     'genus': '/api/v1/families/brassicaceae/genus'}}},
  {'id': 15891,
   'name': 'Abelia',
   'slug': 'abelia',
   'links': {'self': '/api/v1/genus/abelia',
    'plants': '/api/v1/genus/abelia/plants',
    'species': '/api/v1/genus/abelia/species',
    'family': '/api/v1/families/caprifoliaceae'},
   'family': {'id': 126,
    'name': 'Caprifoliaceae',
    'common_name': None,
    'slug': 'caprifoliaceae',
    'links': {'self': '/api/v1/families/caprifoliaceae',
     'division_order': None,
     'genus': '/api/v1/families/caprifoliaceae/genus'}}},
  {'id': 10537,
   'name': 'Abeliophyllum',
   'slug': 'abeliophyllum',
   'links': {'self': '/api/v1/genus/abeliophyllum',
    'plants': '/api/v1/genus/abeliophyllum/plants',
    'species': '/api/v1/genus/abeliophyllum/species',
    'family': '/api/v1/families/oleaceae'},
   'family': {'id': 264,
    'name': 'Oleaceae',
    'common_name': 'Olive family',
    'slug': 'oleaceae',
    'links': {'self': '/api/v1/families/oleaceae',
     'division_order': '/api/v1/division_orders/scrophulariales',
     'genus': '/api/v1/families/oleaceae/genus'}}},
  {'id': 7229,
   'name': 'Abelmoschus',
   'slug': 'abelmoschus',
   'links': {'self': '/api/v1/genus/abelmoschus',
    'plants': '/api/v1/genus/abelmoschus/plants',
    'species': '/api/v1/genus/abelmoschus/species',
    'family': '/api/v1/families/malvaceae'},
   'family': {'id': 115,
    'name': 'Malvaceae',
    'common_name': None,
    'slug': 'malvaceae',
    'links': {'self': '/api/v1/families/malvaceae',
     'division_order': None,
     'genus': '/api/v1/families/malvaceae/genus'}}},
  {'id': 7230,
   'name': 'Abies',
   'slug': 'abies',
   'links': {'self': '/api/v1/genus/abies',
    'plants': '/api/v1/genus/abies/plants',
    'species': '/api/v1/genus/abies/species',
    'family': '/api/v1/families/pinaceae'},
   'family': {'id': 3,
    'name': 'Pinaceae',
    'common_name': 'Pine family',
    'slug': 'pinaceae',
    'links': {'self': '/api/v1/families/pinaceae',
     'division_order': '/api/v1/division_orders/pinales',
     'genus': '/api/v1/families/pinaceae/genus'}}},
  {'id': 13431,
   'name': 'Abietinella',
   'slug': 'abietinella',
   'links': {'self': '/api/v1/genus/abietinella',
    'plants': '/api/v1/genus/abietinella/plants',
    'species': '/api/v1/genus/abietinella/species',
    'family': '/api/v1/families/thuidiaceae'},
   'family': {'id': 501,
    'name': 'Thuidiaceae',
    'common_name': None,
    'slug': 'thuidiaceae',
    'links': {'self': '/api/v1/families/thuidiaceae',
     'division_order': None,
     'genus': '/api/v1/families/thuidiaceae/genus'}}},
  {'id': 15885,
   'name': 'Abildgaardia',
   'slug': 'abildgaardia',
   'links': {'self': '/api/v1/genus/abildgaardia',
    'plants': '/api/v1/genus/abildgaardia/plants',
    'species': '/api/v1/genus/abildgaardia/species',
    'family': '/api/v1/families/cyperaceae'},
   'family': {'id': 5,
    'name': 'Cyperaceae',
    'common_name': 'Sedge family',
    'slug': 'cyperaceae',
    'links': {'self': '/api/v1/families/cyperaceae',
     'division_order': '/api/v1/division_orders/cyperales',
     'genus': '/api/v1/families/cyperaceae/genus'}}},
  {'id': 7231,
   'name': 'Abobra',
   'slug': 'abobra',
   'links': {'self': '/api/v1/genus/abobra',
    'plants': '/api/v1/genus/abobra/plants',
    'species': '/api/v1/genus/abobra/species',
    'family': '/api/v1/families/cucurbitaceae'},
   'family': {'id': 144,
    'name': 'Cucurbitaceae',
    'common_name': None,
    'slug': 'cucurbitaceae',
    'links': {'self': '/api/v1/families/cucurbitaceae',
     'division_order': None,
     'genus': '/api/v1/families/cucurbitaceae/genus'}}},
  {'id': 4199,
   'name': 'Abolboda',
   'slug': 'abolboda',
   'links': {'self': '/api/v1/genus/abolboda',
    'plants': '/api/v1/genus/abolboda/plants',
    'species': '/api/v1/genus/abolboda/species',
    'family': '/api/v1/families/xyridaceae'},
   'family': {'id': 97,
    'name': 'Xyridaceae',
    'common_name': None,
    'slug': 'xyridaceae',
    'links': {'self': '/api/v1/families/xyridaceae',
     'division_order': None,
     'genus': '/api/v1/families/xyridaceae/genus'}}},
  {'id': 14778,
   'name': 'Abrahamia',
   'slug': 'abrahamia',
   'links': {'self': '/api/v1/genus/abrahamia',
    'plants': '/api/v1/genus/abrahamia/plants',
    'species': '/api/v1/genus/abrahamia/species',
    'family': '/api/v1/families/anacardiaceae'},
   'family': {'id': 134,
    'name': 'Anacardiaceae',
    'common_name': None,
    'slug': 'anacardiaceae',
    'links': {'self': '/api/v1/families/anacardiaceae',
     'division_order': None,
     'genus': '/api/v1/families/anacardiaceae/genus'}}},
  {'id': 15671,
   'name': 'Abrodictyum',
   'slug': 'abrodictyum',
   'links': {'self': '/api/v1/genus/abrodictyum',
    'plants': '/api/v1/genus/abrodictyum/plants',
    'species': '/api/v1/genus/abrodictyum/species',
    'family': None},
   'family': None},
  {'id': 7232,
   'name': 'Abroma',
   'slug': 'abroma',
   'links': {'self': '/api/v1/genus/abroma',
    'plants': '/api/v1/genus/abroma/plants',
    'species': '/api/v1/genus/abroma/species',
    'family': '/api/v1/families/malvaceae'},
   'family': {'id': 115,
    'name': 'Malvaceae',
    'common_name': None,
    'slug': 'malvaceae',
    'links': {'self': '/api/v1/families/malvaceae',
     'division_order': None,
     'genus': '/api/v1/families/malvaceae/genus'}}},
  {'id': 7233,
   'name': 'Abronia',
   'slug': 'abronia',
   'links': {'self': '/api/v1/genus/abronia',
    'plants': '/api/v1/genus/abronia/plants',
    'species': '/api/v1/genus/abronia/species',
    'family': '/api/v1/families/nyctaginaceae'},
   'family': {'id': 192,
    'name': 'Nyctaginaceae',
    'common_name': None,
    'slug': 'nyctaginaceae',
    'links': {'self': '/api/v1/families/nyctaginaceae',
     'division_order': None,
     'genus': '/api/v1/families/nyctaginaceae/genus'}}},
  {'id': 7235,
   'name': 'Abrophyllum',
   'slug': 'abrophyllum',
   'links': {'self': '/api/v1/genus/abrophyllum',
    'plants': '/api/v1/genus/abrophyllum/plants',
    'species': '/api/v1/genus/abrophyllum/species',
    'family': '/api/v1/families/rousseaceae'},
   'family': {'id': 296,
    'name': 'Rousseaceae',
    'common_name': None,
    'slug': 'rousseaceae',
    'links': {'self': '/api/v1/families/rousseaceae',
     'division_order': None,
     'genus': '/api/v1/families/rousseaceae/genus'}}}],
 'links': {'self': '/api/v1/genus',
  'first': '/api/v1/genus?page=1',
  'next': '/api/v1/genus?page=2',
  'last': '/api/v1/genus?page=826'},
 'meta': {'total': 16508}}

In [ ]:
trefle_data.keys()

dict_keys(['data', 'links', 'meta'])

In [ ]:
trefle_total_data_points = len(trefle_data['data'])
print(trefle_total_data_points)

20

In [ ]:
import pandas as pd

def prepare_dataframe(data_list):
  trefle_df = pd.DataFrame(data_list)
  return trefle_df

In [ ]:
trefle_df = prepare_dataframe(trefle_data['data'])
trefle_df.head()

,id,name,slug,links,family
0,2552,Aa,aa,"{'self': '/api/v1/genus/aa', 'plants': '/api/v...","{'id': 50, 'name': 'Orchidaceae', 'common_name..."
1,15299,Aakia,aakia,"{'self': '/api/v1/genus/aakia', 'plants': '/ap...","{'id': 7, 'name': 'Poaceae', 'common_name': No..."
2,600,Aaronsohnia,aaronsohnia,"{'self': '/api/v1/genus/aaronsohnia', 'plants'...","{'id': 13, 'name': 'Asteraceae', 'common_name'..."
3,15699,Abacopteris,abacopteris,"{'self': '/api/v1/genus/abacopteris', 'plants'...",None
4,2124,Abarema,abarema,"{'self': '/api/v1/genus/abarema', 'plants': '/...","{'id': 49, 'name': 'Fabaceae', 'common_name': ..."

In [ ]:
len(trefle_df)

20

I noticed links and families needs further refined in order to build the data table that I want to see. I asked Claude how I could parse further and it noted pd.json_normalize() allows nested dictionaries to become their own columns automatically.

In [ ]:
trefle_df = pd.json_normalize(trefle_data['data'])
trefle_df.head()

,id,name,slug,links.self,links.plants,links.species,links.family,family.id,family.name,family.common_name,family.slug,family.links.self,family.links.division_order,family.links.genus,family
0,2552,Aa,aa,/api/v1/genus/aa,/api/v1/genus/aa/plants,/api/v1/genus/aa/species,/api/v1/families/orchidaceae,50.0,Orchidaceae,None,orchidaceae,/api/v1/families/orchidaceae,None,/api/v1/families/orchidaceae/genus,NaN
1,15299,Aakia,aakia,/api/v1/genus/aakia,/api/v1/genus/aakia/plants,/api/v1/genus/aakia/species,/api/v1/families/poaceae,7.0,Poaceae,None,poaceae,/api/v1/families/poaceae,None,/api/v1/families/poaceae/genus,NaN
2,600,Aaronsohnia,aaronsohnia,/api/v1/genus/aaronsohnia,/api/v1/genus/aaronsohnia/plants,/api/v1/genus/aaronsohnia/species,/api/v1/families/asteraceae,13.0,Asteraceae,Aster family,asteraceae,/api/v1/families/asteraceae,/api/v1/division_orders/asterales,/api/v1/families/asteraceae/genus,NaN
3,15699,Abacopteris,abacopteris,/api/v1/genus/abacopteris,/api/v1/genus/abacopteris/plants,/api/v1/genus/abacopteris/species,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2124,Abarema,abarema,/api/v1/genus/abarema,/api/v1/genus/abarema/plants,/api/v1/genus/abarema/species,/api/v1/families/fabaceae,49.0,Fabaceae,None,fabaceae,/api/v1/families/fabaceae,None,/api/v1/families/fabaceae/genus,NaN

In [ ]:
trefle_df.iloc[0]

id                                                           2552
name                                                           Aa
slug                                                           aa
links.self                                       /api/v1/genus/aa
links.plants                              /api/v1/genus/aa/plants
links.species                            /api/v1/genus/aa/species
links.family                         /api/v1/families/orchidaceae
family.id                                                    50.0
family.name                                           Orchidaceae
family.common_name                                           None
family.slug                                           orchidaceae
family.links.self                    /api/v1/families/orchidaceae
family.links.division_order                                  None
family.links.genus             /api/v1/families/orchidaceae/genus
family                                                        NaN
Name: 0, dtype: object

#Reflection on Trefle API

I was able to get a decent amount of information. It looks like I could potentially pass some of the inputs I wanted, but the API is lacking a hardiness zone. Additionally, even with some attempts leveraging Claude to try to help me get an image, the effort to get an image was very high. I think I'm going to try another API.

One thing to note is how the API limitations and pagination would impact an app that I would want to productionize. I'm less concerned about these limitations for testing and prototyping, but it will be a limiting factor as far as how I could scale this prototype to a production-ready app. I have a feeling I'll find the same limitations with all free APIs, but I'll keep looking.

#Perenual API

I got an API Key and am going to see what I can use from Perenual API. Documentation is available here: https://perenual.com/docs/plant-open-api

#Perenual API Investigation

In [ ]:
from google.colab import userdata

PERENUAL_API_KEY = userdata.get("PERENUAL_API")

In [ ]:
# JSON:
perenual_request_url = f"https://perenual.com/api/v2/species-list?key={PERENUAL_API_KEY}"

In [ ]:
import requests

perenual_response = requests.get(perenual_request_url)
print(perenual_response)
print(perenual_response.json())

<Response [200]>

In [ ]:
perenual_data = perenual_response.json()
perenual_data

{'data': [{'id': 1,
   'common_name': 'European Silver Fir',
   'scientific_name': ['Abies alba'],
   'other_name': ['Common Silver Fir'],
   'family': 'Pinaceae',
   'hybrid': None,
   'authority': None,
   'subspecies': None,
   'cultivar': None,
   'variety': None,
   'species_epithet': 'alba',
   'genus': 'Abies',
   'default_image': {'license': 45,
    'license_name': 'Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)',
    'license_url': 'https://creativecommons.org/licenses/by-sa/3.0/deed.en',
    'original_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/1_abies_alba/og/1536px-Abies_alba_SkalitC3A9.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=880e7351e896be232e3af9f3319e979e24af7061e7b16c6d9ac3e103fd1fb2bb',
    'regular_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/1_abies_alba/regular/1536px-Abies_alba_SkalitC3A9.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=daf921b80eb5344f04c117e0f76c4165cff2dc087fd88564e9ea7a5780632881',
    'medium_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/1_abies_alba/medium/1536px-Abies_alba_SkalitC3A9.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=49ffc9757f4d22c52a29650ed5abd777e64e5802b627dcfb9a7318fe67d6ba40',
    'small_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/1_abies_alba/small/1536px-Abies_alba_SkalitC3A9.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=53026e2badad54db96ae1777dc78fb7fa32b32631223c195eb2ffd393cfa93cc',
    'thumbnail': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/1_abies_alba/thumbnail/1536px-Abies_alba_SkalitC3A9.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=7c192e8f97b715e6c2bf6a0c5edfa5eac7cae5a65e3768d1deca2318c8c0dc49'}},
  {'id': 2,
   'common_name': 'Pyramidalis Silver Fir',
   'scientific_name': ["Abies alba 'Pyramidalis'"],
   'other_name': [],
   'family': 'Pinaceae',
   'hybrid': None,
   'authority': None,
   'subspecies': None,
   'cultivar': 'Pyramidalis',
   'variety': None,
   'species_epithet': 'alba',
   'genus': 'Abies',
   'default_image': {'license': 5,
    'license_name': 'Attribution-ShareAlike License',
    'license_url': 'https://creativecommons.org/licenses/by-sa/2.0/',
    'original_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/2_abies_alba_pyramidalis/og/49255769768_df55596553_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=5bffcf14a2ee6c0f487da002f55cc7476e621828163fc001398f8987e8cd77fe',
    'regular_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/2_abies_alba_pyramidalis/regular/49255769768_df55596553_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=c09d4c009697f794e8fc64c4afb8babcc2d0f21c94ee3552815d5df27144792b',
    'medium_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/2_abies_alba_pyramidalis/medium/49255769768_df55596553_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=255648a1fae645c6c3acd71b15841afa695d3c2ca8bdcf321425ca790b60e203',
    'small_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/2_abies_alba_pyramidalis/small/49255769768_df55596553_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=5457855787bc85d685a44082f5c7a1ec28b49756144ca62810c0dab5b2d6d9bb',
    'thumbnail': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/2_abies_alba_pyramidalis/thumbnail/49255769768_df55596553_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=9e2276975da75e034949da24153c0d26b5ecd4f12750f2c4ea6a243f7fd4999e'}},
  {'id': 3,
   'common_name': 'White Fir',
   'scientific_name': ['Abies concolor'],
   'other_name': ['Silver Fir', 'Concolor Fir', 'Colorado Fir'],
   'family': 'Pinaceae',
   'hybrid': None,
   'authority': None,
   'subspecies': None,
   'cultivar': None,
   'variety': None,
   'species_epithet': 'concolor',
   'genus': 'Abies',
   'default_image': {'license': 5,
    'license_name': 'Attribution-ShareAlike License',
    'license_url': 'https://creativecommons.org/licenses/by-sa/2.0/',
    'original_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/3_abies_concolor/og/52292935430_f4f3b22614_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=4c6d100510f33dba671158573803376c6948d2d71a3f541f3e7510cf41aa7520',
    'regular_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/3_abies_concolor/regular/52292935430_f4f3b22614_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=79b05d4f7dfe8252d06568e46033c3ecd3f06f38635e13e798964991814b564d',
    'medium_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/3_abies_concolor/medium/52292935430_f4f3b22614_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=3373e7af806ee0c822275d07cfef0a5ac7f2f1c147090848acf1d092096e4ce9',
    'small_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/3_abies_concolor/small/52292935430_f4f3b22614_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=8251bd5bfed9c858369d74648bcc8541f9163a9908696c705d88b397e3f1cfac',
    'thumbnail': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/3_abies_concolor/thumbnail/52292935430_f4f3b22614_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=9c464ca67a3395f02c7e4fb34269a1ff732de67f556f91f73c78f5a147d3ecfe'}},
  {'id': 4,
   'common_name': 'Candicans White Fir',
   'scientific_name': ["Abies concolor 'Candicans'"],
   'other_name': ['Silver Fir', 'Concolor Fir', 'Colorado Fir'],
   'family': 'Pinaceae',
   'hybrid': None,
   'authority': None,
   'subspecies': None,
   'cultivar': 'Candicans',
   'variety': None,
   'species_epithet': 'concolor',
   'genus': 'Abies',
   'default_image': {'license': 5,
    'license_name': 'Attribution-ShareAlike License',
    'license_url': 'https://creativecommons.org/licenses/by-sa/2.0/',
    'original_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/4_abies_concolor_candicans/og/49283844888_332c9e46f2_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=727ed6a9fcf30cdfa3bd574a640d443255a096d3839a792e4ce0f7140bc6d268',
    'regular_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/4_abies_concolor_candicans/regular/49283844888_332c9e46f2_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=d395adaedb97bdb86e7ca9e8ba8b0815c23e2f3bb9b5d296a124719d15cafaf0',
    'medium_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/4_abies_concolor_candicans/medium/49283844888_332c9e46f2_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=f725e36d6ba8fc5a429227aa4c7719f636143f315556286785633a008174742c',
    'small_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/4_abies_concolor_candicans/small/49283844888_332c9e46f2_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=ccab624eaad03864c4b779504b143a8064a8e4ba7523ca6b479be9eeec658d8b',
    'thumbnail': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/4_abies_concolor_candicans/thumbnail/49283844888_332c9e46f2_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=9677147d6419e23d1f987318e803747b8a53495950769a721aac2717a50f3aa4'}},
  {'id': 5,
   'common_name': 'Fraser Fir',
   'scientific_name': ['Abies fraseri'],
   'other_name': ['Southern Fir'],
   'family': 'Pinaceae',
   'hybrid': None,
   'authority': None,
   'subspecies': None,
   'cultivar': None,
   'variety': None,
   'species_epithet': 'fraseri',
   'genus': 'Abies',
   'default_image': {'license': 4,
    'license_name': 'Attribution License',
    'license_url': 'https://creativecommons.org/licenses/by/2.0/',
    'original_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/5_abies_fraseri/og/36843539702_e80fc436e0_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=af968dd5e159c26c4e75f5debf56d76a63ec877403b62b2f3781efed107caa37',
    'regular_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/5_abies_fraseri/regular/36843539702_e80fc436e0_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=2eafad5722da1724eb274628b6e65af3084fce514a3a5b59e4d803582a8f8322',
    'medium_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/5_abies_fraseri/medium/36843539702_e80fc436e0_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=2cfe0a257198248a351ab4245e33e6855e7cb00ef05b948cdc7ee3fadc981050',
    'small_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/5_abies_fraseri/small/36843539702_e80fc436e0_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=e1f3ee62eb88856751e694e4c892fa19e54bc9910da322029486113b20b76691',
    'thumbnail': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/5_abies_fraseri/thumbnail/36843539702_e80fc436e0_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=73c503ab28c894f593e4a8662c2356117a2b10d26d6f8a3c428ddfb9af7507c5'}},
  {'id': 6,
   'common_name': 'Golden Korean Fir',
   'scientific_name': ["Abies koreana 'Aurea'"],
   'other_name': [],
   'family': 'Pinaceae',
   'hybrid': None,
   'authority': None,
   'subspecies': None,
   'cultivar': 'Aurea',
   'variety': None,
   'species_epithet': 'koreana',
   'genus': 'Abies',
   'default_image': {'license': 5,
    'license_name': 'Attribution-ShareAlike License',
    'license_url': 'https://creativecommons.org/licenses/by-sa/2.0/',
    'original_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/6_abies_koreana_aurea/og/49235570926_99ec10781d_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=d65ccb063e87752a6d01b1089fbb83e8eeb7f52ed5659e41808efbd2d01f2f1f',
    'regular_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/6_abies_koreana_aurea/regular/49235570926_99ec10781d_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=d0da3753b3af7be6c6ee10831f6c04250c4e39856b885e7d76809504a856ce39',
    'medium_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/6_abies_koreana_aurea/medium/49235570926_99ec10781d_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=b49763e0b9aa3c0a3523a0ac0d67f709b650c3665c24240162f5edfe0d916a5f',
    'small_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/6_abies_koreana_aurea/small/49235570926_99ec10781d_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=6a582a9afa56a7fdcfe9bc3e48586df91ad093482dbb39e55ba2a04238e69bbe',
    'thumbnail': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/6_abies_koreana_aurea/thumbnail/49235570926_99ec10781d_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=c920912451e6a534731774e42d111a08a1f078afd024d31cf6ea62fafaae0041'}},
  {'id': 7,
   'common_name': 'Alpine Fir',
   'scientific_name': ['Abies lasiocarpa'],
   'other_name': ['Subalpine Fir', 'Rocky Mountain Fir'],
   'family': 'Pinaceae',
   'hybrid': None,
   'authority': None,
   'subspecies': None,
   'cultivar': None,
   'variety': None,
   'species_epithet': 'lasiocarpa',
   'genus': 'Abies',
   'default_image': {'license': 5,
    'license_name': 'Attribution-ShareAlike License',
    'license_url': 'https://creativecommons.org/licenses/by-sa/2.0/',
    'original_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/7_abies_lasiocarpa/og/51002756843_74fae3c2fa_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=5fb14baa24bb9579139f43a62dead6bf5365ff44dd6508af5ca89e11a21bb409',
    'regular_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/7_abies_lasiocarpa/regular/51002756843_74fae3c2fa_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=ed08effe052bddcff515267b14085c6885b2174d76cfccfd32d5a80396ae41cb',
    'medium_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/7_abies_lasiocarpa/medium/51002756843_74fae3c2fa_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=da28f4689f68ebb9d6af6f3199afe9ea6fda02df19994d574e152df354efc15a',
    'small_url': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/7_abies_lasiocarpa/small/51002756843_74fae3c2fa_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=4f3904d7a46f76d3dc609b19190645430bef50f807b237b1777e2b1b010e7ead',
    'thumbnail': 'https://s3.us-central-1.wasabisys.com/perenual/species_image/7_abies_lasiocarpa/thumbnail/51002756843_74fae3c2fa_b.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0MPGHU7CIPXNPMVWMXUW%2F20260810%2Fus-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260810T001121Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=db04f3b5c8b47e95230f505de27a7da1423934bc1d5dba957dcc311157f6fb06'}},
  {'id': 8,
   'common_name': 'Blue Spanish Fir',
   'scientific_name': ["Abies pinsapo 'Glauca'"],
   'other_name': ['Glaucous Spanish Fir'],
   'family': 'Pinaceae',
   'hybrid': None,
   'authority': None,
   'subspecies': None,
   'cultivar': 'Glauca',
   'variety': None,
   'species_epithet': 'pinsapo',
   'genus': 'Abies',
   'default_image': {'license': 4,
    'license_name': 'Attribution License',
    'license_url': 'https://creativecommons.org/licenses/by/2.0/',

In [ ]:
perenual_data.keys()

dict_keys(['data', 'to', 'per_page', 'current_page', 'from', 'last_page', 'total'])

In [ ]:
perenual_total_data_points = len(perenual_data['data'])
print(perenual_total_data_points)

30

In [ ]:
import pandas as pd

def prepare_dataframe(data_list):
  perenual_df = pd.DataFrame(data_list)
  return perenual_df

In [ ]:
perenual_df = prepare_dataframe(perenual_data['data'])
perenual_df.head()

,id,common_name,scientific_name,other_name,family,hybrid,authority,subspecies,cultivar,variety,species_epithet,genus,default_image
0,1,European Silver Fir,[Abies alba],[Common Silver Fir],Pinaceae,None,None,None,None,None,alba,Abies,"{'license': 45, 'license_name': 'Attribution-S..."
1,2,Pyramidalis Silver Fir,[Abies alba 'Pyramidalis'],[],Pinaceae,None,None,None,Pyramidalis,None,alba,Abies,"{'license': 5, 'license_name': 'Attribution-Sh..."
2,3,White Fir,[Abies concolor],"[Silver Fir, Concolor Fir, Colorado Fir]",Pinaceae,None,None,None,None,None,concolor,Abies,"{'license': 5, 'license_name': 'Attribution-Sh..."
3,4,Candicans White Fir,[Abies concolor 'Candicans'],"[Silver Fir, Concolor Fir, Colorado Fir]",Pinaceae,None,None,None,Candicans,None,concolor,Abies,"{'license': 5, 'license_name': 'Attribution-Sh..."
4,5,Fraser Fir,[Abies fraseri],[Southern Fir],Pinaceae,None,None,None,None,None,fraseri,Abies,"{'license': 4, 'license_name': 'Attribution Li..."

In [ ]:
len(perenual_df)

30

In [ ]:
perenual_df = pd.json_normalize(perenual_data['data'])
perenual_df.head()

,id,common_name,scientific_name,other_name,family,hybrid,authority,subspecies,cultivar,variety,...,genus,default_image.license,default_image.license_name,default_image.license_url,default_image.original_url,default_image.regular_url,default_image.medium_url,default_image.small_url,default_image.thumbnail,default_image
0,1,European Silver Fir,[Abies alba],[Common Silver Fir],Pinaceae,None,None,None,None,None,...,Abies,45.0,Attribution-ShareAlike 3.0 Unported (CC BY-SA ...,https://creativecommons.org/licenses/by-sa/3.0...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,NaN
1,2,Pyramidalis Silver Fir,[Abies alba 'Pyramidalis'],[],Pinaceae,None,None,None,Pyramidalis,None,...,Abies,5.0,Attribution-ShareAlike License,https://creativecommons.org/licenses/by-sa/2.0/,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,NaN
2,3,White Fir,[Abies concolor],"[Silver Fir, Concolor Fir, Colorado Fir]",Pinaceae,None,None,None,None,None,...,Abies,5.0,Attribution-ShareAlike License,https://creativecommons.org/licenses/by-sa/2.0/,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,NaN
3,4,Candicans White Fir,[Abies concolor 'Candicans'],"[Silver Fir, Concolor Fir, Colorado Fir]",Pinaceae,None,None,None,Candicans,None,...,Abies,5.0,Attribution-ShareAlike License,https://creativecommons.org/licenses/by-sa/2.0/,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,NaN
4,5,Fraser Fir,[Abies fraseri],[Southern Fir],Pinaceae,None,None,None,None,None,...,Abies,4.0,Attribution License,https://creativecommons.org/licenses/by/2.0/,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,NaN

In [ ]:
perenual_df.iloc[0]

id                                                                            1
common_name                                                 European Silver Fir
scientific_name                                                    [Abies alba]
other_name                                                  [Common Silver Fir]
family                                                                 Pinaceae
hybrid                                                                     None
authority                                                                  None
subspecies                                                                 None
cultivar                                                                   None
variety                                                                    None
species_epithet                                                            alba
genus                                                                     Abies
default_image.license                                                      45.0
default_image.license_name    Attribution-ShareAlike 3.0 Unported (CC BY-SA ...
default_image.license_url     https://creativecommons.org/licenses/by-sa/3.0...
default_image.original_url    https://s3.us-central-1.wasabisys.com/perenual...
default_image.regular_url     https://s3.us-central-1.wasabisys.com/perenual...
default_image.medium_url      https://s3.us-central-1.wasabisys.com/perenual...
default_image.small_url       https://s3.us-central-1.wasabisys.com/perenual...
default_image.thumbnail       https://s3.us-central-1.wasabisys.com/perenual...
default_image                                                               NaN
Name: 0, dtype: object

In order to add a filter for Zone 7 hardiness zone, I worked with Claude to determine how to add that filter into the URL. Additionally, I noticed hardiness zone is not included in the results I get back to be able to check that the filter is working as expected, so I asked Claude to help me pull that. One thing I noted is this is currently filtering where zone is equal to 7. Despite trying to get Claude to help me refine to get a filter that brings back results where the zone range is inclusive of zone 7 instead of equal to 7, I have yet to be successful with this. It's something I can look further into refining with time. Adding this known issue to my product backlog...

In [ ]:
# Query Perenual's species-list endpoint filtered to USDA hardiness zone 7
perenual_zone7_url = f"https://perenual.com/api/v2/species-list?key={PERENUAL_API_KEY}&hardiness=7"

perenual_zone7_response = requests.get(perenual_zone7_url)
print(perenual_zone7_response)

perenual_zone7_data = perenual_zone7_response.json()
perenual_zone7_df = pd.json_normalize(perenual_zone7_data['data'])

print(f"Found {len(perenual_zone7_df)} species on this page for zone 7")
perenual_zone7_df.head()

<Response [200]>
Found 30 species on this page for zone 7

,id,common_name,scientific_name,other_name,family,hybrid,authority,subspecies,cultivar,variety,...,genus,default_image.license,default_image.license_name,default_image.license_url,default_image.original_url,default_image.regular_url,default_image.medium_url,default_image.small_url,default_image.thumbnail,default_image
0,1,European Silver Fir,[Abies alba],[Common Silver Fir],Pinaceae,None,None,None,None,None,...,Abies,45.0,Attribution-ShareAlike 3.0 Unported (CC BY-SA ...,https://creativecommons.org/licenses/by-sa/3.0...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,NaN
1,8,Blue Spanish Fir,[Abies pinsapo 'Glauca'],[Glaucous Spanish Fir],Pinaceae,None,None,None,Glauca,None,...,Abies,4.0,Attribution License,https://creativecommons.org/licenses/by/2.0/,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,NaN
2,29,Alpenweiss Variegated Dwarf Japanese Maple*,[Acer palmatum 'Alpenweiss'],[],None,None,None,None,Alpenweiss,None,...,Acer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,31,Aoyagi Japanese Maple*,[Acer palmatum 'Aoyagi'],[Green Coral Japanese Maple],None,None,None,None,Aoyagi,None,...,Acer,451.0,CC0 1.0 Universal (CC0 1.0) Public Domain Dedi...,https://creativecommons.org/publicdomain/zero/...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,NaN
4,32,Arakawa Cork Bark Japanese Maple,[Acer palmatum 'Arakawa'],"[Rough-Bark Japanese Maple, Arakawa Ukon]",Sapindaceae,None,None,None,Arakawa,None,...,Acer,45.0,Attribution-ShareAlike 3.0 Unported (CC BY-SA ...,https://creativecommons.org/licenses/by-sa/3.0...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,https://s3.us-central-1.wasabisys.com/perenual...,NaN

In [ ]:
# First row of the zone 7 results
perenual_zone7_df.iloc[0]

id                                                                            1
common_name                                                 European Silver Fir
scientific_name                                                    [Abies alba]
other_name                                                  [Common Silver Fir]
family                                                                 Pinaceae
hybrid                                                                     None
authority                                                                  None
subspecies                                                                 None
cultivar                                                                   None
variety                                                                    None
species_epithet                                                            alba
genus                                                                     Abies
default_image.license                                                      45.0
default_image.license_name    Attribution-ShareAlike 3.0 Unported (CC BY-SA ...
default_image.license_url     https://creativecommons.org/licenses/by-sa/3.0...
default_image.original_url    https://s3.us-central-1.wasabisys.com/perenual...
default_image.regular_url     https://s3.us-central-1.wasabisys.com/perenual...
default_image.medium_url      https://s3.us-central-1.wasabisys.com/perenual...
default_image.small_url       https://s3.us-central-1.wasabisys.com/perenual...
default_image.thumbnail       https://s3.us-central-1.wasabisys.com/perenual...
default_image                                                               NaN
Name: 0, dtype: object

In [ ]:
def get_perenual_hardiness(species_id):
    """Fetch a Perenual species' hardiness zone range via the details endpoint."""
    details_url = f"https://perenual.com/api/v2/species/details/{species_id}?key={PERENUAL_API_KEY}"
    details_response = requests.get(details_url)
    details_data = details_response.json()
    return details_data.get('hardiness')

In [ ]:
# Confirm the filter worked by checking the first zone 7 result's actual hardiness range
first_id = perenual_zone7_df.iloc[0]['id']
first_common_name = perenual_zone7_df.iloc[0]['common_name']

hardiness_range = get_perenual_hardiness(first_id)
print(f"{first_common_name} (id {first_id}) hardiness range: {hardiness_range}")

European Silver Fir (id 1) hardiness range: {'min': '7', 'max': '7'}

One of the other areas Trefle failed at was ease of grabbing an image. I'm going to try that with Perenual.

In [ ]:
from IPython.display import Image, display

# Use the confirmed inclusive-range results if available, otherwise fall back to the raw zone 7 results
if len(perenual_zone7_inclusive_df) > 0:
    result_row = perenual_zone7_inclusive_df.iloc[0]
else:
    result_row = perenual_zone7_df.iloc[0]

print(f"{result_row['common_name']} ({result_row.get('scientific_name')})")

image_url = result_row.get('default_image.medium_url')

if pd.notna(image_url):
    display(Image(url=image_url))
else:
    print("No image available for this species.")

European Silver Fir (['Abies alba'])